General cleanup
This commit contains several changes.

Verbose printing
The form [ $__verbose ] is now used throughout. It uses the [ builtin
to check for $__verbose != NULL. The global variable __verbose is unset
at the beginning of the script, and only set if the -v flag is passed
on the command line. The value of the variable doesn't really matter,
only the fact that it is set at all is what counts.

Function nesting level
The nesting level is increased from 10 to 20. I hit the limit when building
seL4 in its unoptimized form. Since the existing recipe is basically a
translation of the CMake build script, there are many many nested dependencies.
It is possible that 20 is too deep as a default, but I will leave it for
another day to be tuned properly. Even in the case of an infinitely recursive
dependency, 20 levels catches it quickly enough.

Version number
I added a version number __version="1.0" which can be printed from the
command line when _usage() is called (for example, with --help).

Internal functions
All internally defined functions start with an underscore.

Replaced all uses of 'eval' with 'local -n' for passing a variable containing
a name of another variable. This is used for automatically determining
dependencies of a target in a rule without explicitly knowing the target name.

Signed-off-by: Joel Nider <joel@nider.org>

diff --git a/bake b/bake
--- a/bake
+++ b/bake
@@ -13,18 +13,21 @@
 # itself, which begs the question 'why use two languages instead of one?'
 # Thus, 'bake' is the result of bash+make => a bash-based build system
 
-# allow 10 levels of function recursion by default
-FUNCNEST=${NESTING:-10}
+# allow 20 levels of function recursion by default
+# We want enough levels to catch circular dependencies without artificially limiting valid usage
+# This can be overridden on the command line, if necessary
+FUNCNEST=${NESTING:-20}
 #set -x
 
 declare -a rules
 declare -A dep_names
-verbose=false
+unset __verbose
+__version="1.0"
 
-function filter_name()
+function _filter_name()
 {
 	local name=$1 # the name to be filtered
-	local _result=$2 # the return variable to be filled with the filtered name
+	local -n _result=$2 # the return variable to be filled with the filtered name
 
 	# replace . with _
 	name=${name//\./_}
@@ -32,16 +35,27 @@ function filter_name()
 	name=${name//\//_}
 	# replace - with _
 	name=${name//-/_}
-	eval $_result="'$name'"
+	_result=$name
+}
+
+# Return an array containing all of the dependencies of the specified target
+function _deps_of()
+{
+	local target=$1
+	local -n _result=$2 # the return variable to be filled with the dependencies
+	local dep_var_name
+	_filter_name $target dep_var_name
+	local -n dep_list=$dep_var_name
+	_result=${dep_list[@]}
 }
 
 # extract the filename portion of a file (by removing the path)
 # could use external "basename" utility instead
-function filename()
+function _filename()
 {
 	local name=$1
-	local _result=$2
-	eval $_result="'${name##*/}'"
+	local -n _result=$2
+	_result=${name##*/}
 }
 
 # export a list of all rules
@@ -57,42 +71,61 @@ function _find_rules()
 	done
 }
 
+# dump out all discovered rules to stdout
+function _print_rules()
+{
+	echo "All known rules:"
+	for rule in $rules; do
+		echo $rule
+	done
+}
+
 #generic rule for checking the timestamp to see if the target needs to be rebuilt
 # Emulate the behaviour of make. Make targets are built recursively in 2 stages - first
 # the dependencies are built, and then the target itself is built.
 # build() takes 2 main parameters:
 # target: name of the target to build
 # dep_var_name: the name of a variable containing an array of dependencies
-function build()
+function _build_target()
 {
 	local target=$1
 	local dep_var_name=$2
-	local parent_timestamp=$3
-	local parent=$4
+	local outdir=$3
+	local parent_timestamp=$4
+	local parent=$5
 	local rebuild
 	local ret
 	local modified
 	local target_exists
 
+	# make sure output directory exists
+	if [[ ! -d $outdir ]]; then
+		[ $__verbose ] && echo "Creating output directory $outdir"
+		mkdir -p $outdir
+	fi
+
 	# set the 'modified' timestamp
-	! $verbose || echo "Checking for the existence of a target file named '$target'"
-	if [[ -e $target ]]; then
+	[ $__verbose ] && echo "Checking for the existence of a target file named '$outdir/$target'"
+	if [[ -e $outdir/$target ]]; then
 		target_exists=true
 		rebuild=false
-		! $verbose || echo "Target $target exists"
-		if [ -d $target ]; then
+		if [[ -d $outdir/$target ]]; then
 			# directory - recurse into it and build whatever is there
-			! $verbose || echo "Entering directory '$target'"
+			[ $__verbose ] && echo "Entering directory '$target'"
 			pushd .
-			cd $target
-			bake $target ${verbose:+"-v"}
+			parent_dir=$PWD
+			cd $outdir/$target
+			cmd="bake ${__verbose:+"-v"} -p $parent_dir " # $target "
+			[ $__verbose ] && echo $cmd
+			$cmd
 			popd
-		elif [ -f $target ]; then
+		elif [[ -f $outdir/$target ]]; then
 			# regular file
-			modified=$(stat -c %Y "$target")
+			[ $__verbose ] && echo "Target $outdir/$target exists"
+			modified=$(stat -c %Y "$outdir/$target")
 		fi
 	else
-		! $verbose || echo "target file '$target' doesn't exist"
+		[ $__verbose ] && echo "target file '$outdir/$target' doesn't exist"
 		modified=0
 		rebuild=true
 	fi
@@ -104,52 +137,64 @@ function build()
 	# Sometimes, dep_$target isn't a valid identifier (for example, contains '/' in a file path)
 	# For that reason, the name is filtered beforehand.
 	dep_var_name=${dep_names[$target]:-$target}
-	filter_name $dep_var_name dep_var_name
-	! $verbose || echo "Checking dependencies of target $target with dependencies in variable "\$"$dep_var_name"
+	_filter_name $dep_var_name dep_var_name
+	[ $__verbose ] && echo "Checking dependencies of target $target with dependencies in variable "\$"$dep_var_name"
 	local -n dep_list=$dep_var_name
 	if [[ $dep_list ]]; then
-		! $verbose || echo "Dependencies of $target: ${dep_list[*]}"
+		[ $__verbose ] && echo "Dependencies of $target: ${dep_list[*]}"
 
 		## this can be parallelized ##
 		local dep
 		for dep in ${dep_list[*]}; do
 			if [[ $dep ]]; then
 				# filter the target name to create a valid identifier
-				filter_name $dep filtered_dep
-				build $dep dep_names[$filtered_dep] $modified $target
+				_filter_name $dep filtered_dep
+				_build_target $dep dep_names[$filtered_dep] $outdir $modified $target
 				ret=$?
 				if [[ $ret == 255 ]]; then
 					echo "Dependency $dep failed"
 					return $ret
 				elif [[ $ret == 2 ]]; then
-					! $verbose || echo "Prerequisite $dep says we must rebuild $target"
+					[ $__verbose ] && echo "Prerequisite $dep says we must rebuild $target"
 					rebuild=true
 				fi
 
 				# check the timestamp of the dependency to see if the target needs to be rebuilt
-				if [[ -e $dep && $modified != 0 ]]; then
+				if [[ -f $dep && $modified != 0 ]]; then
 					dep_modified=$(stat -c %Y "$dep")
-					! $verbose || echo "Checking timestamp of $dep ($dep_modified) vs $target ($modified)"
+					[ $__verbose ] && echo "Checking timestamp of $dep ($dep_modified) vs $target ($modified)"
 					if [[ $dep_modified > $modified ]]; then
-						! $verbose || echo "$target out of date"
+						[ $__verbose ] && echo "} $target out of date"
 						rebuild=true
 					fi
 				fi
-			#else
-			#	! $verbose || echo "Dependency $dep doesn't have a rule"
 			fi
 		done
-			! $verbose || echo "All dependencies of $target are up to date"
+			[ $__verbose ] && echo "} All dependencies of $target are up to date"
 	else
-		! $verbose || echo "No dependencies"
+		[ $__verbose ] && echo "} No dependencies"
 	fi
 
 	# if all of the prerequisites were already up-to-date, and the target exists, there is nothing to do!
 	$rebuild || return 0
 
+	# check if this exists only as an input file
+	# JKN - this doesn't rebuild out-of-date targets that already exist!
+	#if [[ -f $target ]]; then
+	#	[ $__verbose ] && echo "Found input file $target"
+	#	return 0
+	#fi
+
+	# extract target directory, and make sure it exists
+	local target_dir=${target%/*}
+	if [[ $target_dir != $target && ! -d $target_dir ]]; then
+		[ $__verbose ] && echo "} Creating output directory $target_dir"
+		mkdir -p $target_dir
+	fi
+
 	#rules=(${!rule*})
 	# stage 2: the build steps based on file type or other user-defined rules
-	! $verbose || echo "Looking for rule for target $target"
+	[ $__verbose ] && echo "} Looking for rule for target $target"
 	#echo "Known rules ${rules[*]}"
 	for rule in ${rules[*]}; do
 		$rule "$target"
@@ -157,56 +202,104 @@ function build()
 		#echo "$rule=$ret"
 		if [[ $ret == "0" ]]; then
 			# we found a matching rule
-			! $verbose || echo "rule '$rule' matched"
+			[ $__verbose ] && echo "} rule '$rule' matched"
 			return $ret
 		fi
 	done
-	! $verbose || echo "No matching rule"
+	[ $__verbose ] && echo "No matching rule"
+
+	# check if this exists as an input directory
+	if [[ -d $target ]]; then
+		[ $__verbose ] && echo "Found input directory $target"
+		cmd="bake ${__verbose:+"-v"} -p $target $dep"
+		[ $__verbose ] && echo $cmd
+		$cmd
+		ret=$?
+		return $ret
+	fi
 	return -1 # no rule found to rebuild this target
 }
 
-function usage()
+function _usage()
 {
 	echo "Bake: a bash-based build system"
+	echo "Version: $__version"
+	echo "bake [OPTIONS] [TARGET]"
+	echo "Options:"
 	echo "-f <script>        Specify the recipe file containing build instructions"
+	echo "-h                 This help screen"
+	echo "-o <path>          Specify the output directory for any targets"
+	echo "-p <path>          Specify the script path for a heirarchical build system"
 	echo "-v                 Set 'verbose' mode; usually for debugging the build script"
+	echo ""
+	echo "Special targets:"
+	echo "rules              Print out all user-defined rules"
+	echo "filter_name <string> Print the valid variable name that bake can use"
 }
 
 ### Start here ###
 scriptfile="recipe" # the default script name
+srcdir=$(pwd) # default path
+outdir=$(pwd) # default output directory
 
 # see what options the user is asking for
-while getopts "f:v" option; do
+while getopts "f:ho:p:v" option; do
 	case $option in
 	f)
 		scriptfile=$OPTARG
 		;;
+	o)
+		outdir=$OPTARG
+		;;
+	p)
+		srcdir=$OPTARG
+		;;
 	v)
-		verbose=true
+		__verbose=1
 		;;
 	*)
-		usage
+		_usage
 		exit 0
 		;;
 	esac
 done
 shift $((OPTIND-1))
 
-# read script file
-if [ ! -e $scriptfile ]; then
-	echo "I can't find the script called '$scriptfile' in the directory:" $(pwd)
-	exit -2
-fi
-[ ! $verbose ] || echo "Reading script '$scriptfile'"
-source $scriptfile
-
 # figure out the build target. If a parameter was passed on the command line, use that. Otherwise, look for one called 'main'
 target=${1:-"main"}
-! $verbose || echo "Building target '$target'"
+
+# handle special targets before the script is sourced, in case it has errors
+if [[ $target == "filter_name" ]]; then
+	_filter_name $2 filtered_name
+	[ $__verbose ] && echo "The dependencies will be in a variable called:"
+	echo $filtered_name
+	exit
+elif [ $target == "help" ]; then
+	_usage
+	exit
+fi
+
+# read script file
+if [[ ! -f $srcdir/$scriptfile ]]; then
+	echo "I can't find the script called '$scriptfile' in the directory:" $srcdir
+	exit -2
+fi
+
+[ $__verbose ] && echo "Reading script '$srcdir/$scriptfile'"
+source $srcdir/$scriptfile
 
 # find rules
 rules=$(_find_rules)
 
+# print the rules - this obviously must be done after the script is sourced
+if [[ $target == "rules" ]]; then
+	_print_rules
+	exit
+fi
+
+# build the user-specified target
+[ $__verbose ] && echo "Building target '$target'"
+
 # for each target in the list, build it recursively
-build $target dep_names[$target]
-#echo "Done"
+_build_target $target dep_names[$target] $outdir
+[ $__verbose ] && echo "Done"
